# this programm tells jokes. pretty simple

print ("what do you get when you cross a snowman with a vampire?")
input()
print("frostbite!")
print()
print("what do dentists call an astronaut's cavity?")
input()
print("a black hole!")
print()
print("knock knock")
input()
print("who's there?")
input()
print("interupting cow")
input()
print("interupting cow wh")
print("MOOOOO!")
